
INSERT INTO travel.tourist_details (,tourist_id,first_name, last_name, gender, age, occupation, nationality, language)
VALUES 
(1,'John', 'Doe', 'Male', 30, 'Engineer', 'USA', ARRAY['English']),
(2,'Jane', 'Smith', 'Female', 25, 'Doctor', 'UK', ARRAY['English']),
(3,'Carlos', 'Gonzalez', 'Male', 40, 'Teacher', 'Spain', ARRAY['Spanish']),
(4,'Maria', 'Garcia', 'Female', 35, 'Artist', 'Mexico', ARRAY['Spanish']),
(5,'Liu', 'Wei', 'Male', 28, 'Scientist', 'China', ARRAY['Mandarin']),
(6,'Aisha', 'Khan', 'Female', 32, 'Journalist', 'Pakistan', ARRAY['Urdu']),
(7,'Michael', 'Brown', 'Male', 45, 'Lawyer', 'USA', ARRAY['English']),
(8,'Emily', 'Davis', 'Female', 29, 'Nurse', 'Canada', ARRAY['English', 'French']),
(9,'Raj', 'Patel', 'Male', 38, 'Businessman', 'India', ARRAY['Hindi']),
(10,'Sofia', 'Martinez', 'Female', 27, 'Architect', 'Argentina', ARRAY['Spanish']),
(11,'Ahmed', 'Ali', 'Male', 50, 'Doctor', 'Egypt', ARRAY['Arabic']),
(12,'Yuki', 'Tanaka', 'Female', 24, 'Designer', 'Japan', ARRAY['Japanese']),
(13,'Hans', 'Schmidt', 'Male', 35, 'Engineer', 'Germany', ARRAY['German']),
(14,'Olivia', 'Wilson', 'Female', 31, 'Photographer', 'Australia', ARRAY['English']),
(15,'Nina', 'Ivanova', 'Female', 26, 'Student', 'Russia', ARRAY['Russian']),
(16,'Carlos', 'Silva', 'Male', 44, 'Chef', 'Brazil', ARRAY['Portuguese']),
(17,'Alice', 'Wong', 'Female', 39, 'Entrepreneur', 'Hong Kong', ARRAY['Cantonese']),
(18,'Tom', 'Thompson', 'Male', 28, 'Pilot', 'USA', ARRAY['English']),
(19,'Isabella', 'Rossi', 'Female', 34, 'Scientist', 'Italy', ARRAY['Italian']),
(20,'Lee', 'Chung', 'Male', 41, 'Engineer', 'South Korea', ARRAY['Korean']),
(21,'Fatima', 'Hassan', 'Female', 36, 'Teacher', 'Saudi Arabia', ARRAY['Arabic']),
(22,'David', 'Green', 'Male', 29, 'Musician', 'UK', ARRAY['English']),
(23,'Anna', 'Svensson', 'Female', 37, 'Manager', 'Sweden', ARRAY['Swedish']),
(24,'Luis', 'Torres', 'Male', 42, 'Scientist', 'Spain', ARRAY['Spanish']),
(25,'Emma', 'White', 'Female', 33, 'Engineer', 'New Zealand', ARRAY['English']),
(26,'Lucas', 'Pereira', 'Male', 47, 'Journalist', 'Brazil', ARRAY['Portuguese']),
(27,'Sara', 'Lee', 'Female', 30, 'Doctor', 'South Korea', ARRAY['Korean']),
(28,'Nikolai', 'Petrov', 'Male', 39, 'Businessman', 'Russia', ARRAY['Russian']),
(29,'Eve', 'Nguyen', 'Female', 28, 'Artist', 'Vietnam', ARRAY['Vietnamese']),
(30,'Chen', 'Xiaoming', 'Male', 43, 'Scientist', 'China', ARRAY['Mandarin']),
(31,'Rachel', 'Miller', 'Female', 26, 'Designer', 'USA', ARRAY['English']),
(32,'Oscar', 'Garcia', 'Male', 52, 'Retired', 'Spain', ARRAY['Spanish']),
(33,'Maya', 'Kim', 'Female', 25, 'Student', 'South Korea', ARRAY['Korean']),
(34,'Arjun', 'Mehta', 'Male', 33, 'Teacher', 'India', ARRAY['Hindi']),
(35,'Eva', 'Schneider', 'Female', 38, 'Engineer', 'Germany', ARRAY['German']),
(36,'Paul', 'Clark', 'Male', 48, 'Engineer', 'USA', ARRAY['English']),
(37,'Sophia', 'Harris', 'Female', 29, 'Architect', 'UK', ARRAY['English']),
(38,'Carlos', 'Fernandez', 'Male', 45, 'Scientist', 'Argentina', ARRAY['Spanish']),
(39'Ana', 'Castillo', 'Female', 31, 'Nurse', 'Mexico', ARRAY['Spanish']),
(40,'Ken', 'Watanabe', 'Male', 27, 'Pilot', 'Japan', ARRAY['Japanese']),
(41,'Maria', 'Silva', 'Female', 40, 'Lawyer', 'Portugal', ARRAY['Portuguese']),
(42,'Liam', 'Brown', 'Male', 34, 'Chef', 'Canada', ARRAY['English']),
(43,'Zara', 'Hussein', 'Female', 30, 'Journalist', 'Pakistan', ARRAY['Urdu']),
(44,'John', 'ONeill', 'Male', 50, 'Engineer', 'Ireland', ARRAY['English']),
(45,'Isabel', 'Lopez', 'Female', 25, 'Student', 'Spain', ARRAY['Spanish']),
(46,'Tim', 'Jackson', 'Male', 37, 'Photographer', 'Australia', ARRAY['English']),
(47,'Eva', 'Kozlova', 'Female', 39, 'Scientist', 'Russia', ARRAY['Russian']),
(48,'Roberto', 'Mendez', 'Male', 32, 'Businessman', 'Mexico', ARRAY['Spanish']),
(49,'Alice', 'Murray', 'Female', 27, 'Doctor', 'USA', ARRAY['English']);

