
INSERT INTO travel.city (country_id, city_name) 
VALUES 
(1, 'New York'),
(1, 'Los Angeles'),
(1, 'Chicago'),
(2, 'London'),
(2, 'Manchester'),
(2, 'Birmingham'),
(3, 'Madrid'),
(3, 'Barcelona'),
(3, 'Valencia'),
(4, 'Mexico City'),
(4, 'Guadalajara'),
(4, 'Monterrey'),
(5, 'Beijing'),
(5, 'Shanghai'),
(5, 'Guangzhou'),
(6, 'Karachi'),
(6, 'Lahore'),
(6, 'Islamabad'),
(7, 'Toronto'),
(7, 'Vancouver'),
(7, 'Montreal'),
(8, 'Delhi'),
(8, 'Mumbai'),
(8, 'Bangalore'),
(9, 'Buenos Aires'),
(9, 'Córdoba'),
(9, 'Rosario'),
(10, 'Cairo'),
(10, 'Alexandria'),
(10, 'Giza'),
(11, 'Tokyo'),
(11, 'Osaka'),
(11, 'Nagoya'),
(12, 'Berlin'),
(12, 'Munich'),
(12, 'Frankfurt'),
(13, 'Sydney'),
(13, 'Melbourne'),
(13, 'Brisbane'),
(14, 'Moscow'),
(14, 'Saint Petersburg'),
(14, 'Novosibirsk'),
(15, 'São Paulo'),
(15, 'Rio de Janeiro'),
(15, 'Salvador'),
(16, 'Hong Kong'),
(17, 'Rome'),
(17, 'Milan'),
(17, 'Naples'),
(18, 'Seoul'),
(18, 'Busan'),
(18, 'Incheon'),
(19, 'Riyadh'),
(19, 'Jeddah'),
(19, 'Mecca'),
(20, 'Stockholm'),
(20, 'Gothenburg'),
(20, 'Malmö'),
(21, 'Auckland'),
(21, 'Wellington'),
(21, 'Christchurch'),
(22, 'Hanoi'),
(22, 'Ho Chi Minh City'),
(22, 'Da Nang'),
(23, 'Lisbon'),
(23, 'Porto'),
(23, 'Coimbra'),
(24, 'Dublin'),
(24, 'Cork'),
(24, 'Galway');
